<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="mvcc-PC" name="BatchExecution_Digi.Hybrid" tests="41" failures="0" timestamp="20 Feb 2018 10:19:27 GMT" time="95.163" errors="2">
  <testcase name="AdminLogin_CreatingUsers_AdminLogout" time="0.502" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="Company_Profiles" time="0.248" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="SurveyFlow" time="0.200" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="Create_Survey" time="0.170" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="Update_Survey" time="0.150" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="EndUser_SurveyResponse" time="0.154" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="ResponseValidation" time="0.135" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="createQuiz" time="0.137" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="publishCreatedQuiz" time="0.116" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="UpdateQuiz" time="0.144" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="shareQuizEndUserResponse" time="0.119" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="QuizResponseValidation" time="0.126" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="SavecreatePetition" time="0.113" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="publishSavedPetition" time="0.122" classname="BatchExecution_Digi.Hybrid">
    <error type="atu.testng.reports.exceptions.ATUReporterStepFailedException">
      <![CDATA[[ATU Custom Reporter Step Failed Exception]
	at atu.testng.reports.listeners.ATUReportsListener.onTestSuccess(Unknown Source)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1742)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1722)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:722)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- publishSavedPetition -->
  <testcase name="Peti_AprvRrejectByAdmin" time="0.000" classname="BatchExecution_Digi.Hybrid">
    <skipped/>
  </testcase> <!-- Peti_AprvRrejectByAdmin -->
  <testcase name="validatePetiWebSite" time="0.000" classname="BatchExecution_Digi.Hybrid">
    <skipped/>
  </testcase> <!-- validatePetiWebSite -->
  <testcase name="NewUserSignPetition" time="0.125" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="ExistedUserSignPetition" time="0.135" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="supportTheCause" time="0.116" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="saveCreatedCrowdFund" time="0.115" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="publishSavedCrowdFund" time="0.118" classname="BatchExecution_Digi.Hybrid">
    <error type="atu.testng.reports.exceptions.ATUReporterStepFailedException">
      <![CDATA[[ATU Custom Reporter Step Failed Exception]
	at atu.testng.reports.listeners.ATUReportsListener.onTestSuccess(Unknown Source)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1742)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1722)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:722)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- publishSavedCrowdFund -->
  <testcase name="cf_AprvRrejectByAdmin" time="0.000" classname="BatchExecution_Digi.Hybrid">
    <skipped/>
  </testcase> <!-- cf_AprvRrejectByAdmin -->
  <testcase name="validateCF_WebSite" time="0.000" classname="BatchExecution_Digi.Hybrid">
    <skipped/>
  </testcase> <!-- validateCF_WebSite -->
  <testcase name="supportTheCauseCF" time="0.137" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="supportTheCauseNewUserCF" time="0.116" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="supportTheCauseNewUserPeti" time="0.118" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="commentOnCompanySide" time="0.114" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="peti_replyCommentByExistedUserInWebsite" time="0.136" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="peti_newCommentInWebsite_ByExistedUser" time="0.128" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="peti_replyCommentByNewUserInWebsite" time="0.137" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="peti_newCommentInWebsite_ByNewUser" time="0.117" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="replyCommentOnCompanySide" time="0.116" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="crowdFundCommentOnCompanySide" time="0.107" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="peti_CF_replyCommentByExistedUserInWebsite" time="0.108" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="CF_newCommentInWebsite_ByExistedUser" time="0.109" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="CF_newCommentInWebsite_ByNewUser" time="0.110" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="CF_replyCommentByNewUserInWebsite" time="0.106" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="CF_replyCommentOnCompanySide" time="0.118" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="registerAsIndividual_ReferFriends" time="0.113" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="registerAsCompany_ReferFriends" time="0.110" classname="BatchExecution_Digi.Hybrid"/>
  <testcase name="Login_Logout" time="90.118" classname="BatchExecution_Digi.Hybrid"/>
</testsuite> <!-- BatchExecution_Digi.Hybrid -->
